Here most of the documentation is located.
Call gendoc.sh to generate all *.pdf's from *.tex's:
./gendoc.sh

- root: Documentation about the basics.
--- architecture: Documentation about the core architecture.
--- doxygen: Autogenerated doxygen documentation (execute "doxygen doxyfile" from the root dir (../))
--- misc: Documentation and files related to various topics.
--- tdp: Official Team Description Paper about the BORG team.
--- util: Documentation about architecture modules and utilitily tools. Can be very important, but is not part of the core system.
--- vision: Documentation about the different vision modules.

If you want to create to your own documentation:
- Use the template located under "./util/template.tex"
- Do not add binary files (with the exception of the images) to the repo.
- Add the compiled version to the BORG data directory (not part of this repo!).
